apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev1
  namespace: sample
spec:
  project: default
  destination:
    namespace: sample
    server: https://kubernetes.default.svc
  source:
    directory:
      jsonnet: {}
    path: app/overlays/dev1
    repoURL: https://github.com/Daiki-Kawanuma/argocd-sample.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - Validate=false
    - Delete=false
    - FailOnSharedResource=true
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/template/spec/containers/0/image
    kind: Deployment
